### ISSUE TITLE
ContentTooShortError continuously in logs seems to lead to not downloading correctly

### ISSUE THREAD

**Issue by ezek711** [pboardman/4scanner#77] opened 2020-10-11 19:30 UTC
Hello,

I noticed in the docker logs:
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/site-packages/scanner/downloader.py", line 110, in download
tmp_pic = self.download_image(post)
File "/usr/local/lib/python3.8/site-packages/scanner/downloader.py", line 394, in download_image
urllib.request.urlretrieve(pic_url, out_pic)
File "/usr/local/lib/python3.8/urllib/request.py", line 286, in urlretrieve
raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 2931389 out of 4183105 bytes>

while investigating some folders not populating/empty folders in general. Is there a max size on the json file? Do you know what could cause this?

**Comment by pboardman** [comment] 2020-10-11 23:36
Hey! There shouldn't be a limit, and 4MB is not very large so I'm guessing the problem is elsewhere. I never got this error before, do you get it a lot or only on some specific pictures?

**Comment by ezek711** [comment] 2020-10-12 16:47
Hello, thank you for your quick inquiry! I get this error very frequently in the logs along with a few others:
```
Exception in thread Thread-415:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
conn = connection.create_connection(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1006, in _send_output
self.send(msg)
File "/usr/local/lib/python3.8/http/client.py", line 946, in send
self.connect()
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc2f434a130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='a.4cdn.org', port=80): Max retries exceeded with url: /b/thread/numbers.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2f4206340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
```

**Comment by pboardman** [comment] 2020-10-14 17:03
I'll try see if I can reproduce the error but could it be random internet disconnection on your side? Also do you have a lot of searches in your config file?

**Comment by ezek711** [comment] 2020-10-14 19:04
Actually been getting it on two 500Mb connections (moved recently). I do have a lot of searches, is there a standard way to handle that to automatically space out connections?

**Comment by pboardman** [comment] 2020-10-14 20:41
Ok I think we can rule out the connection drop then, maybe you could try the throttle option (last one in [here](https://github.com/pboardman/4scanner/blob/master/OPTIONS.md#throttle-optional))? Since you have a lot of searches you might get throttled by 4chan's server.

For the caching you could just not add the second volume: `-v /anywhere/else:/root/.4scanner`, it's the volume used for the image cache. If you do that anytime you destroy and recreate your container the cache should not persist

Example:

Instead of doing this:
```
docker run -v /can/be/anywhere:/output -v /anywhere/else:/root/.4scanner lacsap/4scanner
```

Try this:
```
docker run -v /can/be/anywhere:/output lacsap/4scanner
```

When when you want to remove the cache delete your container:
```
docker rm YOUR_CONTAINER_ID
```

then you can start a new container with the same command above (`docker run -v /can/be/anywhere:/output lacsap/4scanner`)

**Comment by ezek711** [comment] 2020-10-18 19:43
I tried a lot of that and it didn't resolve. Seemed to be an issue with docker desktop. I moved over to docker EE and it resolved the issues I was having. Additionally I slit up the json file into 3 different containers. I'm now getting an issue where the process just halts and doesn't continue. Do you have any idea how we can kill if no activity exists in the logs/restart the container every 15 minutes or something like that?

**Comment by pboardman** [comment] 2020-10-20 16:26
Ah, I run docker only on linux so I have no idea how docker desktop work :(

What do you mean by "halts", does it still scan for new threads?

**Comment by ezek711** [comment] 2021-01-18 22:14
halts meaning not scanning for new threads. I switched server to ubuntu and everything seems to be fine. some periodic errors for above, but it never pauses. Must have been issue with DockerEE.

**Comment by pboardman** [comment] 2021-01-19 15:14
That's great! closing issue

**Closed by pboardman** 2021-01-19 15:14 UTC
