### ISSUE TITLE
[Bug] Slow downloads?

### ISSUE THREAD

**Issue by Karlore** [pboardman/4scanner#74] opened 2019-10-29 00:25 UTC
Hello, I am unsure if I am configuring incorrectly or not.

Ubuntu 18.04 Python 3.6.5

Installed via pip3, running and it runs scanner correctly. Segregates by scans, and finds topics and labels them the topic number. However the scanner runs and no images are downloaded. Sometimes it will download one or two, but it will only download them every 5-10 minutes.

**Comment by pboardman** [comment] 2019-10-29 01:12
Hello!

I never came across an issue like that, is there any errors being printed out?
Can you print out the full command line you are using to launch 4scanner?
Is downloading a thread using 4downloader also slow? Example `4downloader http://boards.4channel.org/g/thread/73348285/mpv-the-gui-edition`

**Comment by Karlore** [comment] 2019-10-29 01:16
4scanner -w 3 file.json

Seems to be downloading normally through direct link, just when having a json file passed to it, the issue arises.

**Comment by pboardman** [comment] 2019-10-29 01:50
Hmmm, I guess it could have something to do with the duplicate detection, could you try doing a `rm -r ~/.4scanner/` and run 4scanner again to see if the issue is still there?

**Comment by Karlore** [comment] 2019-10-29 03:37
Seems like it downloaded a few at first (30ish images?) then stopped

**Comment by pboardman** [comment] 2019-10-30 11:57
Weird, gonna try reproducing tonight. stupid question but is it possible that there were only ~30 images in the threads your were scanning?

**Comment by Karlore** [comment] 2019-10-30 19:53
There are multiple folders (with obviously initial image) that are empty. If there's any way I can assist let me know

**Comment by pboardman** [comment] 2019-11-03 22:05
I've tried to reproduce the issue but I can't manage to do it... even tried your python version on ubuntu :(
If you don't mind could you send me the config file you used? (here or use the email on my profile) I'm not sure what else it could be.

**Comment by Karlore** [comment] 2019-11-04 22:43
Here's an example:

{"searches":[
    {
      "imageboard": "4chan",
      "folder_name": "Annie",
      "board": "a",
      "width": ">100",
      "height": ">200",
      "filename": "IMG_",
      "extension": [".jpg", ".png", ".gif", ".webm"],
      "keywords": ["Annie"],
      "check_duplicate": true
    },
	{
      "imageboard": "4chan",
      "folder_name": "mangaka",
      "board": "a",
      "width": ">100",
      "height": ">200",
      "filename": "IMG_",
      "extension": [".jpg", ".png", ".gif", ".webm"],
      "keywords": ["mangaka"],
      "check_duplicate": true
    },
	{
      "imageboard": "4chan",
      "folder_name": "franchise",
      "board": "a",
      "width": ">100",
      "height": ">200",
      "filename": "IMG_",
      "extension": [".jpg", ".png", ".gif", ".webm"],
      "keywords": ["franchise"],
      "check_duplicate": true
    },
	{
      "imageboard": "4chan",
      "folder_name": "Chrome",
      "board": "a",
      "width": ">100",
      "height": ">200",
      "filename": "IMG_",
      "extension": [".jpg", ".png", ".gif", ".webm"],
      "keywords": ["Chrome"],
      "check_duplicate": true
    },
	{
      "imageboard": "4chan",
      "folder_name": "canon",
      "board": "a",
      "width": ">100",
      "height": ">200",
      "filename": "IMG_",
      "extension": [".jpg", ".png", ".gif", ".webm"],
      "keywords": ["canon"],
      "check_duplicate": true
    }
]}

**Comment by pboardman** [comment] 2019-11-05 14:21
Ahh the problem is probably with the `"filename": "IMG_",` parameter! It will only download images containing `IMG_` in their name, which is not a lot of images on /a/. Try removing it from all your searches. You can also remove the `extension` parameter if you want to download images with any extensions.

**Comment by pboardman** [comment] 2019-11-14 13:24
I'll close this issue since I'm pretty sure this was the problem, could you confirm when you get a chance to test it? Feel free to reopen if it didn't fix your problem!

**Closed by pboardman** 2019-11-14 13:24 UTC
Labels: bug
